# Generated by Django 2.0.3 on 2020-02-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAssignment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializationData', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='clinicker.SpecializationDB'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='doctorsAssigned',
            field=models.ManyToManyField(blank=True, related_name='Doctors_assigned', to='clinicker.Doctor'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='staffAssigned',
            field=models.ManyToManyField(blank=True, related_name='Staffs_assigned', to='clinicker.Staffs'),
        ),
    ]
